// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct FbsDateTimeOffset : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FbsDateTimeOffset __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Ticks { get { return __p.bb.GetLong(__p.bb_pos + 0); } }
  public short Offset { get { return __p.bb.GetShort(__p.bb_pos + 8); } }

  public static Offset<FbsDateTimeOffset> CreateFbsDateTimeOffset(FlatBufferBuilder builder, long Ticks, short Offset) {
    builder.Prep(8, 16);
    builder.Pad(6);
    builder.PutShort(Offset);
    builder.PutLong(Ticks);
    return new Offset<FbsDateTimeOffset>(builder.Offset);
  }
};

