// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::FlatBuffers;

public struct FbsGUID : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FbsGUID __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte G00 { get { return __p.bb.Get(__p.bb_pos + 0); } }
  public byte G01 { get { return __p.bb.Get(__p.bb_pos + 1); } }
  public byte G02 { get { return __p.bb.Get(__p.bb_pos + 2); } }
  public byte G03 { get { return __p.bb.Get(__p.bb_pos + 3); } }
  public byte G04 { get { return __p.bb.Get(__p.bb_pos + 4); } }
  public byte G05 { get { return __p.bb.Get(__p.bb_pos + 5); } }
  public byte G06 { get { return __p.bb.Get(__p.bb_pos + 6); } }
  public byte G07 { get { return __p.bb.Get(__p.bb_pos + 7); } }
  public byte G08 { get { return __p.bb.Get(__p.bb_pos + 8); } }
  public byte G09 { get { return __p.bb.Get(__p.bb_pos + 9); } }
  public byte G10 { get { return __p.bb.Get(__p.bb_pos + 10); } }
  public byte G11 { get { return __p.bb.Get(__p.bb_pos + 11); } }
  public byte G12 { get { return __p.bb.Get(__p.bb_pos + 12); } }
  public byte G13 { get { return __p.bb.Get(__p.bb_pos + 13); } }
  public byte G14 { get { return __p.bb.Get(__p.bb_pos + 14); } }
  public byte G15 { get { return __p.bb.Get(__p.bb_pos + 15); } }

  public static Offset<FbsGUID> CreateFbsGUID(FlatBufferBuilder builder, byte G00, byte G01, byte G02, byte G03, byte G04, byte G05, byte G06, byte G07, byte G08, byte G09, byte G10, byte G11, byte G12, byte G13, byte G14, byte G15) {
    builder.Prep(1, 16);
    builder.PutByte(G15);
    builder.PutByte(G14);
    builder.PutByte(G13);
    builder.PutByte(G12);
    builder.PutByte(G11);
    builder.PutByte(G10);
    builder.PutByte(G09);
    builder.PutByte(G08);
    builder.PutByte(G07);
    builder.PutByte(G06);
    builder.PutByte(G05);
    builder.PutByte(G04);
    builder.PutByte(G03);
    builder.PutByte(G02);
    builder.PutByte(G01);
    builder.PutByte(G00);
    return new Offset<FbsGUID>(builder.Offset);
  }
};

