// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KudoProtoBufs/CertificateChain.proto
// </auto-generated>
// Original file comments:
// Get the Cert chain from the Kudo Server 
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace VRWorlds.Schemas.Proto.Kudo {
  public static partial class CertificateChain
  {
    static readonly string __ServiceName = "VRWorlds.Schemas.Proto.Kudo.CertificateChain";

    static readonly grpc::Marshaller<global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest> __Marshaller_VRWorlds_Schemas_Proto_Kudo_CertificateRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::VRWorlds.Schemas.Proto.Kudo.CertificateList> __Marshaller_VRWorlds_Schemas_Proto_Kudo_CertificateList = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::VRWorlds.Schemas.Proto.Kudo.CertificateList.Parser.ParseFrom);

    static readonly grpc::Method<global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest, global::VRWorlds.Schemas.Proto.Kudo.CertificateList> __Method_GetCertificates = new grpc::Method<global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest, global::VRWorlds.Schemas.Proto.Kudo.CertificateList>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCertificates",
        __Marshaller_VRWorlds_Schemas_Proto_Kudo_CertificateRequest,
        __Marshaller_VRWorlds_Schemas_Proto_Kudo_CertificateList);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::VRWorlds.Schemas.Proto.Kudo.CertificateChainReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CertificateChain</summary>
    [grpc::BindServiceMethod(typeof(CertificateChain), "BindService")]
    public abstract partial class CertificateChainBase
    {
      public virtual global::System.Threading.Tasks.Task<global::VRWorlds.Schemas.Proto.Kudo.CertificateList> GetCertificates(global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CertificateChain</summary>
    public partial class CertificateChainClient : grpc::ClientBase<CertificateChainClient>
    {
      /// <summary>Creates a new client for CertificateChain</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CertificateChainClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CertificateChain that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CertificateChainClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CertificateChainClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CertificateChainClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::VRWorlds.Schemas.Proto.Kudo.CertificateList GetCertificates(global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCertificates(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::VRWorlds.Schemas.Proto.Kudo.CertificateList GetCertificates(global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCertificates, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::VRWorlds.Schemas.Proto.Kudo.CertificateList> GetCertificatesAsync(global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCertificatesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::VRWorlds.Schemas.Proto.Kudo.CertificateList> GetCertificatesAsync(global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCertificates, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CertificateChainClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CertificateChainClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CertificateChainBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCertificates, serviceImpl.GetCertificates).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CertificateChainBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetCertificates, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::VRWorlds.Schemas.Proto.Kudo.CertificateRequest, global::VRWorlds.Schemas.Proto.Kudo.CertificateList>(serviceImpl.GetCertificates));
    }

  }
}
#endregion
