// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonProtoBufs/Ping.proto
// </auto-generated>
// Original file comments:
// Common Ping Service (prototype) 
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace CommonProto {
  public static partial class Ping
  {
    static readonly string __ServiceName = "CommonProto.Ping";

    static readonly grpc::Marshaller<global::CommonProto.PingRequest> __Marshaller_CommonProto_PingRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CommonProto.PingRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::CommonProto.PingReturn> __Marshaller_CommonProto_PingReturn = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::CommonProto.PingReturn.Parser.ParseFrom);

    static readonly grpc::Method<global::CommonProto.PingRequest, global::CommonProto.PingReturn> __Method_Ping = new grpc::Method<global::CommonProto.PingRequest, global::CommonProto.PingReturn>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_CommonProto_PingRequest,
        __Marshaller_CommonProto_PingReturn);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::CommonProto.PingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Ping</summary>
    [grpc::BindServiceMethod(typeof(Ping), "BindService")]
    public abstract partial class PingBase
    {
      public virtual global::System.Threading.Tasks.Task<global::CommonProto.PingReturn> Ping(global::CommonProto.PingRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Ping</summary>
    public partial class PingClient : grpc::ClientBase<PingClient>
    {
      /// <summary>Creates a new client for Ping</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PingClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Ping that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PingClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PingClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PingClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::CommonProto.PingReturn Ping(global::CommonProto.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::CommonProto.PingReturn Ping(global::CommonProto.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::CommonProto.PingReturn> PingAsync(global::CommonProto.PingRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::CommonProto.PingReturn> PingAsync(global::CommonProto.PingRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PingClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PingClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PingBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, PingBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::CommonProto.PingRequest, global::CommonProto.PingReturn>(serviceImpl.Ping));
    }

  }
}
#endregion
