// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CommonProtoBufs/Ping.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CommonProto {

  /// <summary>Holder for reflection information generated from CommonProtoBufs/Ping.proto</summary>
  public static partial class PingReflection {

    #region Descriptor
    /// <summary>File descriptor for CommonProtoBufs/Ping.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpDb21tb25Qcm90b0J1ZnMvUGluZy5wcm90bxILQ29tbW9uUHJvdG8aJ1N0",
            "YW5kYXJkc1Byb3RvQnVmcy9EYXRlVGltZU9mZnNldC5wcm90bxodU3RhbmRh",
            "cmRzUHJvdG9CdWZzL0dVSUQucHJvdG8imgEKClBpbmdSZXR1cm4SLQoKU2Vy",
            "dmVyR3VpZBgBIAEoCzIZLlN0YW5kYXJkc1Byb3RvLlByb3RvR3VpZBIrCghL",
            "dWRvR3VpZBgCIAEoCzIZLlN0YW5kYXJkc1Byb3RvLlByb3RvR3VpZBIwCgNO",
            "b3cYAyABKAsyIy5TdGFuZGFyZHNQcm90by5Qcm90b0RhdGVUaW1lT2Zmc2V0",
            "Ig0KC1BpbmdSZXF1ZXN0MkEKBFBpbmcSOQoEUGluZxIYLkNvbW1vblByb3Rv",
            "LlBpbmdSZXF1ZXN0GhcuQ29tbW9uUHJvdG8uUGluZ1JldHVybmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::StandardsProto.DateTimeOffsetReflection.Descriptor, global::StandardsProto.GUIDReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonProto.PingReturn), global::CommonProto.PingReturn.Parser, new[]{ "ServerGuid", "KudoGuid", "Now" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::CommonProto.PingRequest), global::CommonProto.PingRequest.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PingReturn : pb::IMessage<PingReturn> {
    private static readonly pb::MessageParser<PingReturn> _parser = new pb::MessageParser<PingReturn>(() => new PingReturn());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PingReturn> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonProto.PingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReturn() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReturn(PingReturn other) : this() {
      serverGuid_ = other.serverGuid_ != null ? other.serverGuid_.Clone() : null;
      kudoGuid_ = other.kudoGuid_ != null ? other.kudoGuid_.Clone() : null;
      now_ = other.now_ != null ? other.now_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingReturn Clone() {
      return new PingReturn(this);
    }

    /// <summary>Field number for the "ServerGuid" field.</summary>
    public const int ServerGuidFieldNumber = 1;
    private global::StandardsProto.ProtoGuid serverGuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StandardsProto.ProtoGuid ServerGuid {
      get { return serverGuid_; }
      set {
        serverGuid_ = value;
      }
    }

    /// <summary>Field number for the "KudoGuid" field.</summary>
    public const int KudoGuidFieldNumber = 2;
    private global::StandardsProto.ProtoGuid kudoGuid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StandardsProto.ProtoGuid KudoGuid {
      get { return kudoGuid_; }
      set {
        kudoGuid_ = value;
      }
    }

    /// <summary>Field number for the "Now" field.</summary>
    public const int NowFieldNumber = 3;
    private global::StandardsProto.ProtoDateTimeOffset now_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StandardsProto.ProtoDateTimeOffset Now {
      get { return now_; }
      set {
        now_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PingReturn);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PingReturn other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ServerGuid, other.ServerGuid)) return false;
      if (!object.Equals(KudoGuid, other.KudoGuid)) return false;
      if (!object.Equals(Now, other.Now)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (serverGuid_ != null) hash ^= ServerGuid.GetHashCode();
      if (kudoGuid_ != null) hash ^= KudoGuid.GetHashCode();
      if (now_ != null) hash ^= Now.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (serverGuid_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ServerGuid);
      }
      if (kudoGuid_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(KudoGuid);
      }
      if (now_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Now);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (serverGuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ServerGuid);
      }
      if (kudoGuid_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(KudoGuid);
      }
      if (now_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Now);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PingReturn other) {
      if (other == null) {
        return;
      }
      if (other.serverGuid_ != null) {
        if (serverGuid_ == null) {
          ServerGuid = new global::StandardsProto.ProtoGuid();
        }
        ServerGuid.MergeFrom(other.ServerGuid);
      }
      if (other.kudoGuid_ != null) {
        if (kudoGuid_ == null) {
          KudoGuid = new global::StandardsProto.ProtoGuid();
        }
        KudoGuid.MergeFrom(other.KudoGuid);
      }
      if (other.now_ != null) {
        if (now_ == null) {
          Now = new global::StandardsProto.ProtoDateTimeOffset();
        }
        Now.MergeFrom(other.Now);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (serverGuid_ == null) {
              ServerGuid = new global::StandardsProto.ProtoGuid();
            }
            input.ReadMessage(ServerGuid);
            break;
          }
          case 18: {
            if (kudoGuid_ == null) {
              KudoGuid = new global::StandardsProto.ProtoGuid();
            }
            input.ReadMessage(KudoGuid);
            break;
          }
          case 26: {
            if (now_ == null) {
              Now = new global::StandardsProto.ProtoDateTimeOffset();
            }
            input.ReadMessage(Now);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PingRequest : pb::IMessage<PingRequest> {
    private static readonly pb::MessageParser<PingRequest> _parser = new pb::MessageParser<PingRequest>(() => new PingRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PingRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CommonProto.PingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest(PingRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PingRequest Clone() {
      return new PingRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PingRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PingRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PingRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
